spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: mycloud-config-cq-dev
---
spring:
  profiles: test #测试环境
  application:
    name: mycloud-config-cq-test
#UTF-8格式保存