server:
  port: 8201

spring:
  prosiles: dev
  application:
    name:  mycloud-config-client
euraka:
  client:
    server-url:
      defaultZone: http://eureka-dev.com:7001/eureka/

---
server:
  port: 8202

spring:
  prosiles: test
  application:
    name:  mycloud-config-client
euraka:
  client:
    server-url:
      defaultZone: http://eureka-test.com:7001/eureka/